Repository timescale/tsbs, pull requests merged in 2019-05, with the labels that each got.

#75 Combine both TimeInterval types into single type
  cmd/tsbs_generate_queries/databases/cassandra/devops.go
  cmd/tsbs_generate_queries/databases/clickhouse/devops.go
  cmd/tsbs_generate_queries/databases/influx/devops.go
  cmd/tsbs_generate_queries/databases/mongo/devops-naive.go
  cmd/tsbs_generate_queries/databases/mongo/devops.go
  cmd/tsbs_generate_queries/databases/siridb/devops.go
  cmd/tsbs_generate_queries/databases/timescaledb/devops.go
  cmd/tsbs_generate_queries/uses/devops/common.go
  cmd/tsbs_generate_queries/uses/devops/common_test.go
  cmd/tsbs_generate_queries/utils/time_interval.go
  cmd/tsbs_run_queries_cassandra/client_side_index.go
  cmd/tsbs_run_queries_cassandra/query.go
  cmd/tsbs_run_queries_cassandra/query_executor.go
  cmd/tsbs_run_queries_cassandra/query_plan.go
  cmd/tsbs_run_queries_cassandra/time_util.go
  internal/utils/time_interval.go
  internal/utils/time_interval_test.go
Labels: refactor

#77 Refactor generate_queries devops case to use errs
  cmd/tsbs_generate_queries/databases/cassandra/devops.go
  cmd/tsbs_generate_queries/databases/clickhouse/devops.go
  cmd/tsbs_generate_queries/databases/influx/devops.go
  cmd/tsbs_generate_queries/databases/mongo/devops-naive.go
  cmd/tsbs_generate_queries/databases/mongo/devops.go
  cmd/tsbs_generate_queries/databases/siridb/devops.go
  cmd/tsbs_generate_queries/databases/timescaledb/devops.go
  cmd/tsbs_generate_queries/uses/devops/common.go
  cmd/tsbs_generate_queries/uses/devops/common_test.go
Labels: refactor

#78 Rename DevopsGenerator to QueryGenerator
  cmd/tsbs_generate_queries/uses/devops/common.go
  cmd/tsbs_generate_queries/uses/devops/groupby.go
  cmd/tsbs_generate_queries/uses/devops/groupby_orderby_limit.go
  cmd/tsbs_generate_queries/uses/devops/high_cpu.go
  cmd/tsbs_generate_queries/uses/devops/lastpoint.go
  cmd/tsbs_generate_queries/uses/devops/max_all_cpu.go
  cmd/tsbs_generate_queries/uses/devops/single_groupby.go
  cmd/tsbs_generate_queries/utils/query_generator.go
  internal/inputs/generator_queries.go
  internal/inputs/generator_queries_test.go
Labels: refactor

#76 Add unit tests to query generation functions for various databases
  cmd/tsbs_generate_queries/databases/clickhouse/devops_test.go
  cmd/tsbs_generate_queries/databases/influx/devops_test.go
  cmd/tsbs_generate_queries/databases/siridb/devops_test.go
Labels: testing

#74 Make statProcessor an interface and create tests for BencRunner
  query/benchmarker.go
  query/benchmarker_test.go
  query/stat_processor.go
  query/stat_processor_test.go
Labels: refactor, testing
